#!/bin/bash

# update working tree
cd {{pod_dir}}/apps/{{app}}
env -i git pull

# install dependencies in case changed
npm install --production

# pod restart will not use latest env variables in config
pod stop {{app}}
pod cleanlogs {{app}}
pod start {{app}}